/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Homework9 */

#ifndef _Included_Homework9
#define _Included_Homework9
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Homework9
 * Method:    convert
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_Homework9_convert
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
